exclude: "deploy/.*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: "mkdocs.yml"
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^tests/data/
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.272'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
